using paycell_web_sdk_client.Models.model;

namespace paycell_web_sdk_client.Models.refund
{
    public class RefundRequest
    {

        /**
         * Header information of the request
         */
        public RequestHeader RequestHeader { get; set; }

        /**
         * Merchant code: defined by Paycell Web SDK for each merchant
         */
        public string MerchantCode { get; set; }

        /**
         * Phone number of the customer
         * County code must be added
         */
        public string Msisdn { get; set; }

        /**
         * payment reference number of the payment that is subject to refund
         */
        public string OriginalReferenceNumber { get; set; }

        /**
         * Uniqie id of the refund operation: generated by merchant
         */
        public string ReferenceNumber { get; set; }

        /**
         * Amount of money that will be refunded. Last 2 digits represent cois.
         * 1.00 represented as "100"
         * 1.66 represented as "166"
         */
        public string Amount { get; set; }
    }
}