using paycell_web_sdk_client.Models.model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace paycell_web_sdk_client.Models.queryStatu
{
    public class QueryStatuRequest
    {
        /**
         * Original payment reference number: Generated by merchant during init phase
         */
        public string OriginalPaymentReferenceNumber { get; set; }

        /**
         * Merchant code: Defined by Paycell Web SDK for each Merchant
         */
        public string MerchantCode { get; set; }

        /**
         * Request Header information
         */
        public RequestHeader RequestHeader { get; set; }
    }
}