using paycell_web_sdk_client.Models.model;

namespace paycell_web_sdk_client.Models.queryStatu
{
    public class QueryStatuResponse
    {
        /**
         * Header information of the response
         */
        public ResponseHeader ResponseHeader { get; set; }

        /**
         * Extra parameters
         */
        public string ExtraParameters { get; set; }

        /**
         * Acquirer bank code information is returned,
         * exists for Paycell Card and Credit Card payments
         */
        public string AcquirerbankCode { get; set; }

        /**
         * Phone number of the customer
         */
        public string Msisdn { get; set; }

        /**
         * Total amount of the payment
         */
        public string Amount { get; set; }

        /**
         * Approval code information
         */
        public string ApprovalCode { get; set; }

        /**
         * Currency information,
         * 99 for TL
         */
        public string Currency { get; set; }

        /**
         * Instalment count, "1" for in advance payment
         */
        public string InstallmentCount { get; set; }

        /**
         * Order ID information
         */
        public string OrderId { get; set; }

        /**
         * Security method used for payment
         * - THREED_SECIRE
         * - NON_THREED_SECURE
         */
        public string PaymentSecurity { get; set; }

        /**
         * Date of the payment is taken
         */
        public string PaymentDate { get; set; }

        /**
         * Reconcilation date of the payment
         */
        public string ReconcilationDate { get; set; }

        /**
         * Unique id of the payment, generated by merchant
         */
        public string PaymentReferenceNumber { get; set; }

        /**
         * Issuer Bank Code information,
         * exists for paycell card and credit card payments.
         */
        public string IssuerBankCode { get; set; }

        /**
         * Status of the payment
         * - 0: Payment is successful
         * - 1: Payment is reversed
         * - 2: Payment is refunded
         * - 3: Payment is not found
         * - 4: Payment is pending
         * - 5: Unknown response
         * - 6: Error or Timeout occurred
         */
        public string Status { get; set; }

        /**
         * Status detail is given
         */
        public string StatusExplanation { get; set; }

        /**
         * Payment method used for the payment
         */
        public PaymentMethod PaymentMethod { get; set; }
    }
}